1rstnumber = int(input("Cual es tu primer numero?"))
2ndnumber = int(input("Cual es tu segundo numero?"))
operacion = int(input(Que operacion quieres hacer?))
if operacion = Suma = print("1rstnumber+2ndnumber")
if operacion = Resta = print("1rstnumber-2ndnumber")
if operacion = Multiplicacion = print("1rstnumber*2ndnumber")
if else print("Lo siento no puedo hacerlo")